# Manual trigger to deploy DevBox
trigger: none

pool:
  vmImage: 'ubuntu-latest'

# Deploy DevBox resources
steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    # Service connect requires 'Microsoft.Authorization/roleAssignments/write' permissions
    azureResourceManagerConnection: 'DevBox-Deploy'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-DevBox'
    location: 'canadacentral'
    templateLocation: 'Linked artifact'
    csmFile: './src/main.bicep'
    csmParametersFile: './src/main.parameters.jsonc'
    deploymentMode: Incremental
